baseURL = "https://hakuna-automata.com/"
languageCode = "en-us"
title = "Hakuna Automata!"
theme = "hyde"

[params]
  description = "Developing software and people"
  # layoutReverse = true

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/cmpaul/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/cmpaul/"}
  ]